export const START_FETCH_DETAIL = "START_FETCH_DETAIL";
export const FINISH_FETCH_DETAIL = "FINISH_FETCH_DETAIL";
export const TOGGLE_ITEM_ATTR = "TOGGLE_ITEM_ATTR"
export const CLOSE_ALERT = "CLOSE_ALERT"
export const TOGGLE_POPUP = "TOGGLE_POPUP";
 