export const START_FETCH_LIST = "START_FETCH_LIST";
export const FINISH_FETCH_LIST = "FINISH_FETCH_LIST";
export const START_GET_STORE = "START_GET_STORE";
export const FINISH_GET_STORE = "FINISH_GET_STORE";